### ISSUE TITLE
【TODO】处理失效的网站

### ISSUE THREAD

**Issue by linlinzzo** [travellings-link/travellings#1351]
- [x] 371，https://zhaobanxian.top 内容404
- [x] https://blog.zggsong.cn/
- [x] https://blog.libw.cc/
- [x] https://iguangdie.xyz/
- [x] blog.luyaoguagua.top 没有开往徽标
- [x] blog.coolchong.cn
- [x] bigcake.cakemc.top 没有开往徽标
- [x] mm.yaomomo.com （没有发现问题）
- [x] moefishtang.xyz
- [x] aibofan.com
- [x] 347（已经处理了？）
- [x] 467（已经处理了？）
- [ ] 371
- [ ] 76    https://moshanghua.net/
- [ ] https://blog.moej.cn/
- [ ] https://blog.imoasislee.com/
- [ ] https://moshanghua.net/
- [ ] https://wasabi.fun/ 没有开往徽标
- [ ] https://jimmyqin.com/
- [ ] https://blog.zggsong.cn/
- [ ] https://hasaik.com/
- [ ] https://www.leejean.top/
- [ ] https://youdef.com/
- [ ] https://www.heson10.com/
- [ ] https://blog.yxqin.top/

把放在那一个多月的单子处理一下。

**Comment by linlinzzo** [comment]
https://zisu.dev/ 没有发现开往徽标

**Comment by linlinzzo** [comment]
https://blog.feizhuqwq.com/ 无连接

**Comment by rabbitxuanxuan** [comment]
https://oi.saiodgm.gq 无法访问
